sudo: required
services:
  - docker

before_install:
  - docker build -t bbafford/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run CI=true bbafford/react-test npm test -- --coverage

after_success:
  - docker build -t bbafford/multi-client ./client
  - docker build -t bbafford/multi-nginx ./nginx
  - docker build -t bbafford/multi-server ./server
  - docker build -t bbafford/multi-worker ./worker

#login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push images to docker hub
  - docker push bbafford/multi-client 
  - docker push bbafford/multi-nginx  
  - docker push bbafford/multi-server
  - docker push bbafford/multi-worker 


